---
# vars file for ansible-role-docker-ce
docker_systemd_service_config_tweaks: []
docker_service_envs: {}

docker_repository_related_packages:
  Amazon:
    - yum-utils   
  CentOS:
    - yum-utils
  RedHat:
    - yum-utils
  Ubuntu:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  Debian:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

docker_repository_url:
  Amazon: https://download.docker.com/linux/centos/docker-ce.repo
  CentOS: https://download.docker.com/linux/centos/docker-ce.repo
  RedHat: https://download.docker.com/linux/centos/docker-ce.repo
  Fedora: https://download.docker.com/linux/fedora/docker-ce.repo

docker_cmd_check_edge_repo_status:
  Amazon: yum-config-manager docker-ce-edge | grep enabled
  CentOS: yum-config-manager docker-ce-edge | grep enabled
  RedHat: yum-config-manager docker-ce-edge | grep enabled
  Fedora: dnf config-manager --dump docker-ce-edge | grep enabled
  Ubuntu: cat /etc/apt/sources.list.d/docker-ce.list | grep edge

docker_cmd_enable_disable_edge_repo:
  Amazon: yum-config-manager --{{ (docker_enable_ce_edge == true) | ternary('enable','disable') }} docker-ce-edge
  CentOS: yum-config-manager --{{ (docker_enable_ce_edge == true) | ternary('enable','disable') }} docker-ce-edge
  RedHat: yum-config-manager --{{ (docker_enable_ce_edge == true) | ternary('enable','disable') }} docker-ce-edge
  Fedora: dnf config-manager --set-{{ (docker_enable_ce_edge == true) | ternary('enabled','disabled') }} docker-ce-edge

docker_cmd_update_repo_cache:
  Amazon: yum makecache fast
  CentOS: yum makecache fast
  RedHat: yum makecache fast
  Fedora: dnf makecache fast
  Ubuntu: apt-get update
  Debian: apt-get update

docker_envs_dir:
  Amazon: /etc/sysconfig
  CentOS: /etc/sysconfig
  RedHat: /etc/sysconfig
  Fedora: /etc/sysconfig
  Ubuntu: /etc/default
  Debian: /etc/default

docker_old_packages:
  Amazon:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  CentOS:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  RedHat:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  Fedora:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  Ubuntu:
    - docker
    - docker-engine
    - docker.io
  Debian:
    - docker
    - docker-engine
    - docker.io

docker_predefined_packages_os: []

docker_predefined_packages_pip:
  Amazon:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
  CentOS:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
  RedHat:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
  Fedora:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
  Ubuntu:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
  Debian:
    sdk:
      - docker
    compose:
      - docker-compose
    stack:
      - jsondiff
      - pyyaml
